---
# install from fs
- when: 
  - un_install_with_fs_src != None
  - un_install_with_git_url == None
  block:

  - name: Create tmp dir "{{ un_install_with_fs_tmp }}"
    ansible.builtin.file:
      path: "{{ un_install_with_fs_tmp }}"
      mode: u=rwx,g=rwx,o=
      state: directory

  # sync to tmp
  - name: Sync "{{ un_install_with_fs_src }}" to "{{ un_install_with_fs_tmp }}"
    become: false
    delegate_to: localhost
    ansible.builtin.command: /usr/bin/rsync --recursive -e ssh {{ un_install_with_fs_src }}/ ansible@{{ inventory_hostname }}:{{ un_install_with_fs_tmp }}

  # copy to dst
  - name: Copy "{{ un_install_with_fs_tmp }}" to "{{ un_install_dst_path }}"
    become: true
    ansible.builtin.command:
      cmd: "cp --archive {{ un_install_with_fs_tmp }}/. {{ un_install_dst_path }}"