---
- tags: [role-un-install-desktop]
  when:
  - un_install_state == "present"
  - un_install_desktop is not None
  - un_install_desktop is not string
  - un_install_desktop is not mapping
  - un_install_desktop is iterable
  - un_install_desktop | length > 0
  block:

  # mkdir
  - name: Mkdir {{ un_install_desktop_dst | dirname }}
    become: true
    ansible.builtin.file:
      state: directory
      path: "{{ un_install_desktop_dst | dirname }}"
      owner: "{{ un_install_user if un_install_desktop_dst.startswith('/home/') else 'root' }}"
      group: "{{ un_install_user if un_install_desktop_dst.startswith('/home/') else 'root' }}"
      mode: u=rwx,g=r,o=r

  # template
  - name: Template .desktop file {{ un_install_desktop_dst }}
    become: true
    loop: "{{ desktop_entries }}"
    ansible.builtin.template:
      src: desktop.j2
      dest: "{{ un_install_desktop_dst }}"
      owner: "{{ un_install_user if un_install_desktop_dst.startswith('/home/') else 'root' }}"
      group: "{{ un_install_user if un_install_desktop_dst.startswith('/home/') else 'root' }}"
      mode: u=rw,g=,o=r

- tags: [role-un-install-desktop]
  when: 
  - un_install_state == "absent"
  - un_install_desktop_dst != None
  - un_install_app in un_install_desktop_dst
  block:
  
  # remove
  - name: Remove {{ un_install_desktop_dst }}
    become: true
    ansible.builtin.file:
      path: "{{ un_install_desktop_dst }}"
      state: absent